openapi: 3.0.3
info:
  title: CloudTuner Kubernetes Cost API
  description: |
    CloudTuner API extensions for Kubernetes cost management and optimization
    integrated with Kubecost data sources.
  version: 1.3.0
  contact:
    name: CloudTuner Support
    email: support@cloudtuner.ai

servers:
- url: http://localhost:8999/api
  description: Local development server
- url: https://api.cloudtuner.ai
  description: Production server

tags:
- name: kubernetes
  description: Kubernetes cluster cost management
- name: costs
  description: Cost allocation and analysis
- name: optimization
  description: Cost optimization recommendations

paths:
  /v1/kubernetes/clusters:
    get:
      tags: [kubernetes]
      summary: List all monitored Kubernetes clusters
      description: Returns a list of all Kubernetes clusters being monitored by CloudTuner
      responses:
        '200':
          description: List of monitored clusters
          content:
            application/json:
              schema:
                type: object
                properties:
                  clusters:
                    type: array
                    items:
                      $ref: '#/components/schemas/Cluster'
                  total:
                    type: integer
                    description: Total number of clusters
                  
  /v1/kubernetes/clusters/{clusterId}:
    get:
      tags: [kubernetes]
      summary: Get cluster details
      parameters:
      - name: clusterId
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Cluster details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cluster'
                
  /v1/kubernetes/clusters/{clusterId}/costs:
    get:
      tags: [costs]
      summary: Get cluster cost breakdown
      parameters:
      - name: clusterId
        in: path
        required: true
        schema:
          type: string
      - name: window
        in: query
        schema:
          type: string
          enum: [1h, 1d, 7d, 30d]
          default: 1d
      - name: aggregate
        in: query
        schema:
          type: string
          enum: [cluster, namespace, pod, service, node]
          default: namespace
      - name: startTime
        in: query
        schema:
          type: string
          format: date-time
      - name: endTime
        in: query
        schema:
          type: string
          format: date-time
      responses:
        '200':
          description: Cluster cost breakdown
          content:
            application/json:
              schema:
                type: object
                properties:
                  window:
                    type: string
                  aggregate:
                    type: string
                  totalCost:
                    type: number
                    format: float
                  breakdown:
                    type: array
                    items:
                      $ref: '#/components/schemas/CostAllocation'
                      
  /v1/kubernetes/clusters/{clusterId}/namespaces:
    get:
      tags: [kubernetes, costs]
      summary: Get namespace cost breakdown
      parameters:
      - name: clusterId
        in: path
        required: true
        schema:
          type: string
      - name: window
        in: query
        schema:
          type: string
          default: 1d
      responses:
        '200':
          description: Namespace cost breakdown
          content:
            application/json:
              schema:
                type: object
                properties:
                  namespaces:
                    type: array
                    items:
                      $ref: '#/components/schemas/NamespaceCost'
                      
  /v1/kubernetes/clusters/{clusterId}/namespaces/{namespace}/workloads:
    get:
      tags: [kubernetes, costs]
      summary: Get workload costs within a namespace
      parameters:
      - name: clusterId
        in: path
        required: true
        schema:
          type: string
      - name: namespace
        in: path
        required: true
        schema:
          type: string
      - name: window
        in: query
        schema:
          type: string
          default: 1d
      responses:
        '200':
          description: Workload cost breakdown
          content:
            application/json:
              schema:
                type: object
                properties:
                  workloads:
                    type: array
                    items:
                      $ref: '#/components/schemas/WorkloadCost'
                      
  /v1/kubernetes/clusters/{clusterId}/assets:
    get:
      tags: [kubernetes, costs]
      summary: Get infrastructure asset costs
      parameters:
      - name: clusterId
        in: path
        required: true
        schema:
          type: string
      - name: assetType
        in: query
        schema:
          type: string
          enum: [Node, LoadBalancer, Disk, Network]
      responses:
        '200':
          description: Infrastructure asset costs
          content:
            application/json:
              schema:
                type: object
                properties:
                  assets:
                    type: array
                    items:
                      $ref: '#/components/schemas/AssetCost'
                      
  /v1/kubernetes/clusters/{clusterId}/optimization:
    get:
      tags: [optimization]
      summary: Get cost optimization recommendations
      parameters:
      - name: clusterId
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Cost optimization recommendations
          content:
            application/json:
              schema:
                type: object
                properties:
                  totalPotentialSavings:
                    type: number
                    format: float
                  recommendations:
                    type: array
                    items:
                      $ref: '#/components/schemas/OptimizationRecommendation'
                      
  /v1/kubernetes/clusters/{clusterId}/metrics:
    get:
      tags: [kubernetes]
      summary: Get cluster resource utilization metrics
      parameters:
      - name: clusterId
        in: path
        required: true
        schema:
          type: string
      - name: metric
        in: query
        schema:
          type: string
          enum: [cpu, memory, network, storage]
      - name: window
        in: query
        schema:
          type: string
          default: 1h
      responses:
        '200':
          description: Resource utilization metrics
          content:
            application/json:
              schema:
                type: object
                properties:
                  metrics:
                    type: array
                    items:
                      $ref: '#/components/schemas/ResourceMetric'

components:
  schemas:
    Cluster:
      type: object
      properties:
        id:
          type: string
          description: Cluster identifier
        name:
          type: string
          description: Cluster name
        provider:
          type: string
          enum: [AWS, GCP, Azure, OnPremise]
        region:
          type: string
        nodeCount:
          type: integer
        status:
          type: string
          enum: [active, inactive, error]
        lastSeen:
          type: string
          format: date-time
        totalMonthlyCost:
          type: number
          format: float
        kubecostVersion:
          type: string
          
    CostAllocation:
      type: object
      properties:
        name:
          type: string
          description: Name of the allocation unit (namespace, pod, etc.)
        window:
          type: object
          properties:
            start:
              type: string
              format: date-time
            end:
              type: string
              format: date-time
        totalCost:
          type: number
          format: float
        cpuCost:
          type: number
          format: float
        memoryCost:
          type: number
          format: float
        networkCost:
          type: number
          format: float
        storageCost:
          type: number
          format: float
        efficiency:
          type: number
          format: float
          description: Resource efficiency score (0-1)
        properties:
          type: object
          additionalProperties:
            type: string
            
    NamespaceCost:
      type: object
      properties:
        namespace:
          type: string
        totalCost:
          type: number
          format: float
        podCount:
          type: integer
        resourceQuota:
          type: object
          properties:
            cpu:
              type: string
            memory:
              type: string
        utilization:
          type: object
          properties:
            cpu:
              type: number
              format: float
            memory:
              type: number
              format: float
        trends:
          type: object
          properties:
            costTrend:
              type: string
              enum: [increasing, decreasing, stable]
            utilizationTrend:
              type: string
              enum: [increasing, decreasing, stable]
              
    WorkloadCost:
      type: object
      properties:
        name:
          type: string
        type:
          type: string
          enum: [Deployment, StatefulSet, DaemonSet, Job, CronJob]
        totalCost:
          type: number
          format: float
        replicas:
          type: integer
        resourceRequests:
          type: object
          properties:
            cpu:
              type: string
            memory:
              type: string
        resourceLimits:
          type: object
          properties:
            cpu:
              type: string
            memory:
              type: string
        actualUsage:
          type: object
          properties:
            cpu:
              type: number
              format: float
            memory:
              type: number
              format: float
        efficiency:
          type: number
          format: float
          
    AssetCost:
      type: object
      properties:
        name:
          type: string
        type:
          type: string
          enum: [Node, LoadBalancer, Disk, Network]
        totalCost:
          type: number
          format: float
        specs:
          type: object
          additionalProperties:
            type: string
        utilization:
          type: object
          properties:
            cpu:
              type: number
              format: float
            memory:
              type: number
              format: float
            disk:
              type: number
              format: float
        provider:
          type: string
        region:
          type: string
        zone:
          type: string
          
    OptimizationRecommendation:
      type: object
      properties:
        id:
          type: string
        type:
          type: string
          enum: [rightsizing, unused_resources, reserved_instances, spot_instances]
        title:
          type: string
        description:
          type: string
        severity:
          type: string
          enum: [low, medium, high, critical]
        potentialSavings:
          type: number
          format: float
        confidence:
          type: number
          format: float
          description: Confidence level (0-1)
        resourceType:
          type: string
        resourceName:
          type: string
        currentConfig:
          type: object
          additionalProperties: true
        recommendedConfig:
          type: object
          additionalProperties: true
        implementation:
          type: object
          properties:
            effort:
              type: string
              enum: [low, medium, high]
            risk:
              type: string
              enum: [low, medium, high]
            steps:
              type: array
              items:
                type: string
                
    ResourceMetric:
      type: object
      properties:
        timestamp:
          type: string
          format: date-time
        metricName:
          type: string
        value:
          type: number
          format: float
        unit:
          type: string
        labels:
          type: object
          additionalProperties:
            type: string