/**
 * Nayara Energy Dashboard - Application Logic
 * Petrol Pump Analytics Dashboard
 * 
 * Connects to analytics_output.json for real-time data
 */

// ============================================
// Configuration
// ============================================

const CONFIG = {
    // Path to analytics JSON (generated by backend)
    analyticsPath: '../prod ready/analytics_output.json',

    // Refresh intervals (ms)
    statsRefresh: 5000,
    alertsRefresh: 10000,
    chartsRefresh: 30000,

    // Demo mode (use sample data when true)
    demoMode: true,
};

// ============================================
// Sample Data (for demo)
// ============================================

const SAMPLE_DATA = {
    stats: {
        cameras: 18,
        staff: 7,
        queue: 3,
        fire: 1,
        sop: 4,
        alerts: 2,
    },
    alerts: [
        {
            id: 1,
            type: 'uniform',
            message: 'Uniform is currently unaccounted for at Bay 2.',
            time: '8:30 AM',
            location: 'Pump 2',
            icon: '👔'
        },
        {
            id: 2,
            type: 'fire',
            message: 'Fire extinguisher is missing at Pump #3.',
            time: '11:45 AM',
            location: 'Pump 3',
            icon: '🔥'
        },
        {
            id: 3,
            type: 'queue',
            message: 'There are five vehicles queued at Queue 1.',
            time: '6:30 PM',
            location: 'Pump 5',
            icon: '🚗'
        },
        {
            id: 4,
            type: 'theft',
            message: 'A theft has occurred here.',
            time: '9:15 AM',
            location: 'Pump 4',
            icon: '⚠️'
        },
        {
            id: 5,
            type: 'tank',
            message: 'Tank 1 is depleted.',
            time: '2:45 PM',
            location: 'Pump 1',
            icon: '⛽'
        }
    ],
    incidents: {
        uniform: 65,
        fire: 15,
        queue: 45,
        tank: 35,
        theft: 40
    },
    hourlyData: {
        labels: Array.from({ length: 24 }, (_, i) => `${i}:00`),
        people: [8, 5, 3, 2, 4, 6, 10, 15, 18, 20, 19, 17, 16, 18, 20, 22, 19, 16, 14, 12, 10, 9, 8, 7],
        vehicles: [120, 80, 45, 30, 40, 90, 180, 220, 240, 200, 180, 160, 150, 170, 200, 250, 280, 260, 200, 150, 130, 120, 100, 90]
    }
};

// ============================================
// Data Fetching
// ============================================

async function fetchAnalytics() {
    if (CONFIG.demoMode) {
        return SAMPLE_DATA;
    }

    try {
        const response = await fetch(CONFIG.analyticsPath);
        if (!response.ok) throw new Error('Failed to fetch');
        return await response.json();
    } catch (error) {
        console.warn('Using sample data:', error.message);
        return SAMPLE_DATA;
    }
}

// ============================================
// Stats Update
// ============================================

function updateStats(data) {
    const stats = data.stats || SAMPLE_DATA.stats;

    animateValue('stat-cameras', stats.cameras);
    animateValue('stat-staff', stats.staff);
    animateValue('stat-queue', stats.queue);
    animateValue('stat-fire', stats.fire);
    animateValue('stat-sop', stats.sop);
    animateValue('stat-alerts', stats.alerts);
}

function animateValue(elementId, newValue) {
    const element = document.getElementById(elementId);
    if (!element) return;

    const currentValue = parseInt(element.textContent) || 0;

    if (currentValue === newValue) return;

    const duration = 500;
    const startTime = performance.now();

    function update(currentTime) {
        const elapsed = currentTime - startTime;
        const progress = Math.min(elapsed / duration, 1);

        const value = Math.round(currentValue + (newValue - currentValue) * easeOutCubic(progress));
        element.textContent = value;

        if (progress < 1) {
            requestAnimationFrame(update);
        }
    }

    requestAnimationFrame(update);
}

function easeOutCubic(t) {
    return 1 - Math.pow(1 - t, 3);
}

// ============================================
// Alerts Update
// ============================================

function updateAlerts(data) {
    const alerts = data.alerts || SAMPLE_DATA.alerts;
    const container = document.getElementById('alerts-list');
    if (!container) return;

    container.innerHTML = alerts.map(alert => `
        <div class="alert-item alert-${alert.type}">
            <div class="alert-icon">${alert.icon}</div>
            <div class="alert-content">
                <span class="alert-message">${alert.message}</span>
                <span class="alert-meta">Today ${alert.time} • ${alert.location}</span>
            </div>
        </div>
    `).join('');
}

// ============================================
// Charts
// ============================================

let categoryChart = null;
let lineChart = null;
let footfallChart = null;

function initCharts() {
    initCategoryChart();
    initLineChart();
    initFootfallChart();
}

function initCategoryChart() {
    const ctx = document.getElementById('categoryChart');
    if (!ctx) return;

    const data = SAMPLE_DATA.incidents;

    categoryChart = new Chart(ctx, {
        type: 'bar',
        data: {
            labels: ['Uniform', 'Fire', 'Queue', 'Tank', 'Theft'],
            datasets: [{
                data: [data.uniform, data.fire, data.queue, data.tank, data.theft],
                backgroundColor: [
                    '#3B82F6',
                    '#EF4444',
                    '#F59E0B',
                    '#6366F1',
                    '#8B5CF6'
                ],
                borderRadius: 4,
                barThickness: 24,
            }]
        },
        options: {
            indexAxis: 'y',
            responsive: true,
            maintainAspectRatio: false,
            plugins: {
                legend: { display: false }
            },
            scales: {
                x: {
                    beginAtZero: true,
                    grid: { display: false }
                },
                y: {
                    grid: { display: false }
                }
            }
        }
    });
}

function initLineChart() {
    const ctx = document.getElementById('incidentLineChart');
    if (!ctx) return;

    // Generate sample trend data
    const labels = ['1:00', '5:00', '8:00', '11:00', '14:00', '17:00', '20:00', '23:00'];
    const data = [2, 4, 3, 7, 5, 8, 4, 3];

    lineChart = new Chart(ctx, {
        type: 'line',
        data: {
            labels: labels,
            datasets: [{
                data: data,
                borderColor: '#3B82F6',
                backgroundColor: 'rgba(59, 130, 246, 0.1)',
                fill: true,
                tension: 0.4,
                pointRadius: 4,
                pointBackgroundColor: '#3B82F6',
            }]
        },
        options: {
            responsive: true,
            maintainAspectRatio: false,
            plugins: {
                legend: { display: false }
            },
            scales: {
                x: {
                    grid: { display: false }
                },
                y: {
                    beginAtZero: true,
                    grid: { color: '#E2E8F0' }
                }
            }
        }
    });
}

function initFootfallChart() {
    const ctx = document.getElementById('footfallChart');
    if (!ctx) return;

    const data = SAMPLE_DATA.hourlyData;

    footfallChart = new Chart(ctx, {
        type: 'line',
        data: {
            labels: data.labels,
            datasets: [
                {
                    label: 'People',
                    data: data.people,
                    borderColor: '#EF4444',
                    backgroundColor: 'transparent',
                    tension: 0.4,
                    pointRadius: 0,
                    borderWidth: 2,
                    yAxisID: 'y'
                },
                {
                    label: 'Vehicles',
                    data: data.vehicles,
                    borderColor: '#3B82F6',
                    backgroundColor: 'rgba(59, 130, 246, 0.1)',
                    fill: true,
                    tension: 0.4,
                    pointRadius: 0,
                    borderWidth: 2,
                    yAxisID: 'y1'
                }
            ]
        },
        options: {
            responsive: true,
            maintainAspectRatio: false,
            interaction: {
                mode: 'index',
                intersect: false,
            },
            plugins: {
                legend: {
                    position: 'top',
                    align: 'end',
                    labels: {
                        boxWidth: 12,
                        usePointStyle: true,
                        pointStyle: 'circle'
                    }
                }
            },
            scales: {
                x: {
                    grid: { display: false }
                },
                y: {
                    type: 'linear',
                    display: true,
                    position: 'left',
                    grid: { color: '#E2E8F0' },
                    title: {
                        display: true,
                        text: 'People'
                    }
                },
                y1: {
                    type: 'linear',
                    display: true,
                    position: 'right',
                    grid: { display: false },
                    title: {
                        display: true,
                        text: 'Vehicles'
                    }
                }
            }
        }
    });
}

function updateCharts(data) {
    // Update chart data if needed
    // For now, charts use sample data
}

// ============================================
// Real-time Updates
// ============================================

function startRealTimeUpdates() {
    // Update stats
    setInterval(async () => {
        const data = await fetchAnalytics();
        updateStats(data);
    }, CONFIG.statsRefresh);

    // Update alerts
    setInterval(async () => {
        const data = await fetchAnalytics();
        updateAlerts(data);
    }, CONFIG.alertsRefresh);

    // Simulate live camera indicators
    simulateLiveCameras();
}

function simulateLiveCameras() {
    const feeds = document.querySelectorAll('.cctv-feed');

    feeds.forEach(feed => {
        // Add recording indicator
        const indicator = document.createElement('div');
        indicator.className = 'recording-indicator';
        indicator.innerHTML = '● REC';
        indicator.style.cssText = `
            position: absolute;
            top: 8px;
            right: 8px;
            background: rgba(239, 68, 68, 0.9);
            color: white;
            padding: 2px 8px;
            border-radius: 4px;
            font-size: 10px;
            font-weight: 600;
            animation: pulse 2s infinite;
        `;
        feed.appendChild(indicator);
    });
}

// ============================================
// Time Display
// ============================================

function updateTime() {
    const now = new Date();
    const timeStr = now.toLocaleTimeString('en-US', {
        hour: '2-digit',
        minute: '2-digit',
        hour12: true
    });

    const locationSpan = document.querySelector('.station-location');
    if (locationSpan) {
        locationSpan.textContent = `Pump 27 - Viman Nagar | Today - Local time ${timeStr}`;
    }
}

// ============================================
// Initialize
// ============================================

document.addEventListener('DOMContentLoaded', async () => {
    console.log('🚀 Nayara Dashboard Initialized');

    // Initial data load
    const data = await fetchAnalytics();
    updateStats(data);
    updateAlerts(data);

    // Initialize charts
    initCharts();

    // Start real-time updates
    startRealTimeUpdates();

    // Update time
    updateTime();
    setInterval(updateTime, 60000);

    // Add click handlers for cameras
    document.querySelectorAll('.cctv-feed').forEach(feed => {
        feed.addEventListener('click', () => {
            const camera = feed.dataset.camera;
            console.log(`Camera ${camera} clicked`);
            // Could open fullscreen view
        });
    });
});

// ============================================
// Export for external use
// ============================================

window.NayaraDashboard = {
    refresh: fetchAnalytics,
    updateStats,
    updateAlerts,
    updateCharts,
    CONFIG
};
